name: Deploy Coffee-Shop2 to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Configure GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 3. Upload site files (deploy everything needed for the site)
      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: |    # root folder containing index.html, CSS, js, img
            ./index.html
            ./CSS
            ./js
            ./img
            ./style.css
            ./script.js

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
